@host =https://localhost:8443/cadastroapi/actrl/update/password
@token= JWT-TOKEN

### START-UPDATE-PASSWORD
POST {{host}}/start
Content-Type: application/json

{
  "email": ""
}

###VALIDATE-UPDATE-CODE
POST {{host}}/validate/code
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "code": ""
}

###UPDARE-PASSWORD
PUT {{host}}/new/password
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "newPassword": "",
  "confirmPassword": ""
}




